apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
spec:
  replicas: 2
  template:
    spec:
      # containers:
      #   - name: assets
      #     volumeMounts:
      #       - name: fsxz-fs
      #         mountPath: /fsxz
      volumes:
        - name: fsxz-fs
          persistentVolumeClaim:
            claimName: fsxz-fs-pvc
